[project]
name = "artist-getter"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "django",
    "pycurl",
    "python-Levenshtein"
]
requires-python = ">= 3.8"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

